baseURL: https://example.org/
languageCode: en-us
defaultContentLanguage: en-us
title: Mayra's Creaciones
theme: hugo-tranquilpeak-theme
disqusShortname: hugo-tranquilpeak-theme
paginate: 7
canonifyurls: yes
permalinks:
  post: /:year/:month/:slug/
taxonomies:
  archive: archives
  category: categories
  tag: tags
author:
  bio: Sewer, Quilter, and Translator of Data
  name: Mayra Smith-Coronado 
  # picture: https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png
  picture: img/profile_photo_square.png
menu:
  main:
    - identifier: home
      name: <strong>Home</strong>
      pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      url: /
      weight: 1
    - identifier: about
      name: About
      pre: <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      url: /#about
      weight: 2
    - identifier: categories
      name: Categories
      pre: <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      url: /categories
      weight: 3
    - identifier: tags
      name: Tags
      pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      url: /tags
      weight: 4
    # - identifier: templates
    #   name: Blog Templates
    #   pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
    #   url: /templates
    #   weight: 4
      
params:
  autoThumbnailImage: yes
  clearReading: yes
  coverImage: img/fabric_photo2.png
  description: Hugo tranquilpeak theme demo
  header:
    rightLink:
      class: ''
      icon: ''
      url: /#about
  hierarchicalCategories: yes
  imageGallery: yes
  sharingOptions:
    - icon: fa-instagram
      name: Instagram
      url: https://www.instagram.com/mayra.smithcoronado/
  sidebarBehavior: 1
  syntaxHighlighter: highlight.js
  thumbnailImage: yes
  thumbnailImagePosition: bottom
